import type { Metadata } from "next";
import { JetBrains_Mono, Roboto_Slab, Geist, EB_Garamond, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header/Header";

const ebGaramondHeading = EB_Garamond({subsets:['latin'],variable:'--font-heading'});

const robotoSlab = Roboto_Slab({subsets:['latin'],variable:'--font-serif'});

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ru" suppressHydrationWarning className={cn("h-full", "antialiased", "pt-3 ", jetbrainsMono.variable, robotoSlab.variable, "font-sans", inter.variable, ebGaramondHeading.variable)}>
      <body className="bg-background min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
