import type { Metadata } from "next";
import { Manrope, JetBrains_Mono, Roboto_Slab } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
// import { ThemeProvider } from "@teispace/next-themes";
import Header from "@/components/layout/header/Header";

const robotoSlab = Roboto_Slab({subsets:['latin'],variable:'--font-serif'});

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const manrope = Manrope({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="ru" suppressHydrationWarning className={cn("h-full", "antialiased", "pt-3 ", manrope.variable, jetbrainsMono.variable, "font-serif", robotoSlab.variable)}>
      <body className="min-h-full flex flex-col">
        {/* <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          forcedTheme={undefined}
        > */}
          <Header />
          {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
