name: Frontend CI

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Node setup (БЕЗ проблемного cache-dependency-path)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install deps
        run: npm ci

      # Type check
      - name: TypeScript check
        run: npx tsc --noEmit

      # Lint
      - name: Lint
        run: npm run lint

      # Build Next.js
      - name: Build
        run: npm run build